### ISSUE TITLE
darken and lighten func issues

### ISSUE THREAD

**Issue by jdh-acct** [richard243/CoolColourLibrary#1]
1) the darken and lighten functions are the same code and, as written, always give a lighten effect
- to get a darken effect, the percent should be entered as a negative value
- to correct this, for darken either invert the p calculation or change the return as follows:
...
return UIColor(red: c.red - p, green: c.green - p, blue: c.blue - p, alpha: c.alpha)
...

2) syntax for darken/lighten does not match the Chameleon syntax
- Chameleon uses darken(byPercentage: CGFloat) and uses values between 0 and 1
- CoolColourLibrary uses darken(percent: CGFloat) and uses values between 0 and 100

**Comment by richard243** [comment]
Thnaks for letting me know. I've fixed both issues.

**Comment by jdh-acct** [comment]
Thanks. Implemented and works as expected 😀

I did open another issue as to the syntax not matching but that is more for reference for anyone taking Angela’s course who is trying to use it. There was another call that also had slightly different syntax but these don’t really need to be fixed. A good exercise for the students to look at the code which makes it easy to do right.

Cheers,
jim
