### ISSUE TITLE
darken/lighten syntax different from that used in Chameleon

### ISSUE THREAD

**Issue by jdh-acct** [richard243/CoolColourLibrary#2]
Just for those trying to use this instead of Chameleon (for example, those taking the Udemy coarse 'iOS & Swift - The COmplete iOS App Development Bootcamp', the functionality of the 'darken' call now matches. The call syntax is different as shown here.

Chameleon:
  color.darkenByPercentage(percentage: CGFloat)

CoolColourLibrary
  color.darken(percent: CGFloat)

**Comment by richard243** [comment]
I've added a darken and lighten by percentage function now. :)
